.Dd $Mdocdate: November 21 2025 $
.Dt RECORDCTL 8
.Os
.Sh NAME
.Nm recordctl
.Nd manipulate controls for audio and video recording
.Sh SYNOPSIS
.Nm
.Op Fl adh
.Nm
.Op Fl n
.Fl t
.Nm
.Op Fl n
.Ar name ...
.Nm
.Op Fl q
.Ar name Ns = Ns Ar value ...
.Nm
.Op Fl c Ar seconds
.Fl m
.Sh DESCRIPTION
The 
.Nm
utility can display or manipulate controls of
.Xr sysctl 8 ,
.Xr sndiod 8 ,
and
.Xr rcctl 8
for audio and video recording, especially: enable or disable audio and/or video recording in the kernel by setting the
.Cm kern.audio.record
and
.Cm kern.video.record
.Xr sysctl 8
variables, respectively; enable or disable an audio monitor mix in the
.Xr sndiod 8
server by updating flags and restarting the process via
.Xr rcctl 8 .
.Pp
The options are as follows:
.Bl -tag -width "-c seconds"
.It Fl a
Display the value of all recording controls. This is the default, if no parameters
are given to 
.Nm .
.It Fl c Ar seconds
Set the number of seconds delay between checks of the state of
.Xr sysctl 8
variables and
.Xr sndiod 8
process and
.Xr rcctl 8
flags, when operating in monitoring mode using the
.Cm -m
option.
.It Fl d
Dump the raw list of available controls and exit.  Useful as a debugging tool.
.It Fl m
Monitor and display audio and video recording controls changes. Output format is the same as
.Xr sndioctl 1
.Cm -m
monitor option.
.It Fl n
Suppress printing of the control name. Useful for setting shell variables. For example, to set the recordable shell variable to the state of audio recording:
.Pp
.Dl # set recordable=`recordctl -n record.audio`
.It Fl q
Suppress all output when setting a control value. This option overrides the behaviour of 
.Fl n .
.It Fl t
Toggle the value of the
.Cm kern.audio.record
and 
.Cm kern.video.record
.Xr sysctl 8
controls to their opposite value instead of setting an explicit value. All other controls specified will be ignored.
.It Ar name Ns Op = Ns Ar value
Retrieve the specified control
.Ar name ,
or attempt to set it to
.Ar value .
Multiple
.Ar name Ns Op = Ns Ar value
arguments may be given.
.El
.Pp
If no controls are specified, all recording control names and values are displayed
on
.Em stdout .
Unless
.Fl d ,
.Fl m ,
or
.Fl n
are used, displayed lines are valid controls.
.Pp
The set of available controls is:
.Pp
.Bl -column "record.audio" "Equivalent To" -offset indent
.It Sy "Name" Ta Sy "Equivalent To"
.It Dv "record.audio" Ta "sysctl kern.audio.record"
.It Dv "record.video" Ta "sysctl kern.video.record"
.It Dv "mix.monitor" Ta "rcctl get sndiod flags"
.El
.Pp
The general format (in both getting and setting a control value) is:
.Pp
.D1 function.name=value
.Pp
The
.Ar function 
can have values like
.Dq record 
or
.Dq mix ,
indicating that the control affects the recording or mixing functions, respectively.
The
.Ar name
indicates what part of the function the control affects.
.Pp
The
.Ar value
can be either 0 or 1, corresponding to the 
.Em off
or
.Em on
states, respectively. If
.Qq \&!
is used instead of a number, then the value is toggled to the opposite state (0 -> 1 or 1 -> 0).
.Pp
If the
.Em -t
option is specified, both
.Cm record.audio
and
.Cm record.video
control values are toggled to their opposite state (0 -> 1 or 1 -> 0) with the variable names and values displayed on
.Em stdout . Any specific controls specified are ignored.

.Sh EXAMPLES
Show all recording controls and their values:
.Pp
.Dl $ recordctl
.Dl record.audio=0
.Dl record.video=0
.Dl mix.monitor=0
.Pp
Toggle both audio and video recording:
.Pp
.Dl # recordctl -t
.Dl record.audio=1
.Dl record.video=1
.Pp
Enable only audio recording and supress output:
.Pp
.Dl # recordctl -q record.audio=1
.Pp
Toggle only video recording:
.Pp
.Dl # recordctl record.video=!
.Dl record.video=0
.Pp
Check whether
.Xr sndiod 8
is configured for a monitor mix:
.Pp
.Dl $ recordctl mix.monitor
.Dl mix.monitor=0
.Pp
Configure
.Xr sndiod 8
for a monitor mix, including restarting the process if necessary:
.Pp
.Dl # recordctl mix.monitor=1
.Dl mix.monitor=1
.Sh SEE ALSO
.Xr sysctl 8 ,
.Xr mixerctl 8 ,
.Xr sndioctl 1 ,
.Xr sndiod 8 ,
.Xr rcctl 8
.Sh HISTORY
Version 0.3 introduced the
.Fl m
option, monitoring and displaying changes to recording controls, and the
.Fl d
option, displaying all controls and their potential values, equivalent to their respective
.Xr sndioctl 1
options. It also introduced the
.Cm mix.monitor
control which corresponds to whether
.Xr sndiod 8
is configured to expose a monitor mix of all audio being ouput by the system.
.Pp
Version 0.2 introduced a significant change in the options and parameters syntax, switching to a primarily control-based syntax similar to
.Xr sysctl 8 ,
.Xr mixerctl 8 ,
and
.Xr sndioctl 1 .
